# Generated by Django 4.1.7 on 2023-03-24 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("script", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in-progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
